### ISSUE TITLE
Windows github action is broken

### ISSUE THREAD

**Issue by hadware** [bootphon/phonemizer#124]
Festival's install on windows seems to be broken.

From the action's log, it seems that speech_tools's download produces a semi-empty file.
I tested the links for both festival and speech-tools, they're working fine when we `wget` them.

@mmmaat Any ideas? Should I still deploy version 3.2.0 ?

**Comment by mmmaat** [comment]
Well... the setup of the Windows CI was... well... a pain.

Few ideas. 
* Instead of `windows-latest` which appears to Windows 2022, maybe try `windows-2019`. I guess it used that version the first time I set up the CI. Unfortunately, I cannot find anywhere in the actions logs a case that is working but not using the festival.exe from action cache...
* Try to split the "Install festival" step in two: "Install speech-tools" and "Install festival", maybe the logs will be clearer? 
* Or more simply comment the "Install festival" part and the `PHONEMIZER_FESTIVAL_EXECUTABLE: "C:\\festival\\src\\main\\festival.exe"` line in the `windows.yaml` file. This will deactivate the festival-based tests under Windows. I guess this is an acceptable solution.

**Comment by hadware** [comment]
This only happens on PR's for some reason... Nothing to see here then.
