### ISSUE TITLE
Citing phonemizer

### ISSUE THREAD

**Issue by cainesap** [bootphon/phonemizer#4]
Hi,
Is there a citation for phonemizer? Or simply the website.
One of my students is writing up her dissertation and wishes to refer to it :)
Andrew

**Comment by mmmaat** [comment]
Hi Andrew!

The proper way to cite softwares is to use zenodo: I'll make a new release (phonemizer-0.3) that will have an attached citable DOI. So that you cite a specific version of the project and make reproduction of your paper easier!

@alecristia are you agree? Or is there a better way to cite phonemizer?

**Comment by mmmaat** [comment]
Ok that's done. Welcome to phonemizer-0.3.1 :)
https://zenodo.org/record/1045826 (or see the badge on the github's README.md)
